package diff

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsGeneratedFile(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(t.TempDir())
	generatedPath := filepath.Join(dir, "generated.go")
	regularPath := filepath.Join(dir, "regular.go")

	if err := os.WriteFile(generatedPath, []byte("// Code generated by mockgen. DO NOT EDIT.\npackage x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(regularPath, []byte("package x\n\nfunc f() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if !IsGeneratedFile(dir, "generated.go") {
		t.Fatal("expected relative path to be detected as generated")
	}
	if !IsGeneratedFile(dir, generatedPath) {
		t.Fatal("expected absolute path to be detected as generated")
	}
	if IsGeneratedFile(dir, "regular.go") {
		t.Fatal("expected regular source file not to be detected as generated")
	}
	if IsGeneratedFile(dir, "missing.go") {
		t.Fatal("expected missing source file not to be detected as generated")
	}
}

func TestCollectPaths_SkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte("// Code generated by mockgen. DO NOT EDIT.\npackage x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "regular.go"), []byte("package x\n\nfunc f() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	filter := Filter{
		DiffGlobs: []string{"*.go"},
		Includes: func(path string) bool {
			return strings.HasSuffix(path, ".go") &&
				!strings.HasSuffix(path, "_test.go") &&
				!IsGeneratedFile(dir, path)
		},
	}

	r, err := CollectPaths(dir, []string{"."}, filter)
	if err != nil {
		t.Fatalf("CollectPaths error: %v", err)
	}
	if len(r.Files) != 1 {
		t.Fatalf("expected 1 analyzable file, got %d", len(r.Files))
	}
	if r.Files[0].Path != "regular.go" {
		t.Fatalf("path = %q, want regular.go", r.Files[0].Path)
	}
}

func TestParseUnifiedDiff_SkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte("// Code generated by mockgen. DO NOT EDIT.\npackage x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "regular.go"), []byte("package x\n\nfunc f() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	filter := Filter{
		DiffGlobs: []string{"*.go"},
		Includes: func(path string) bool {
			return strings.HasSuffix(path, ".go") &&
				!strings.HasSuffix(path, "_test.go") &&
				!IsGeneratedFile(dir, path)
		},
	}

	input := `diff --git a/generated.go b/generated.go
--- a/generated.go
+++ b/generated.go
@@ -0,0 +1,2 @@
+// Code generated by mockgen. DO NOT EDIT.
+package x
diff --git a/regular.go b/regular.go
--- a/regular.go
+++ b/regular.go
@@ -0,0 +1,3 @@
+package x
+
+func f() {}
`

	files, err := parseUnifiedDiff(input, filter)
	if err != nil {
		t.Fatalf("parseUnifiedDiff error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("expected 1 analyzable file, got %d", len(files))
	}
	if files[0].Path != "regular.go" {
		t.Fatalf("path = %q, want regular.go", files[0].Path)
	}
}
